#!/usr/bin/env bash

# Install Kodi Autostart files to operational directories

set -e

if [ $(id -u) -ne 0 ]; then
    echo "Root privileges are required for running $0."
    exit 1
fi

MY_DIR=$(dirname $0)
systemd='/etc/systemd/system/'
unit='kodi.service'
sbin='/usr/local/sbin/'
script='kodi-autostart'
sbinscript="$sbin/$script"
presteam='pre-steam'
sbinpresteam="$sbin/$presteam"

systemctl stop "$unit"

cp "$MY_DIR/$unit" "$systemd"
cp "$MY_DIR/$script" "$MY_DIR/$presteam" "$sbin"

chown kodi:kodi "$sbinscript" "$sbinpresteam"
chmod u+x "$sbinscript" "$sbinpresteam"

systemctl daemon-reload
systemctl start "$unit"
