#!/usr/bin/env bash

# Install Kodi Autostart files to operational directories

set -e

if [ $(id -u) -ne 0 ]; then
    echo "Root privileges are required for running $0."
    exit 1
fi

MY_DIR=$(dirname $0)
systemd='/etc/systemd/system/'
unit='kodi.service'
sbin='/usr/local/sbin/'
script='kodi-autostart'
sbinscript="$sbin/$script"
dummy='kodi-dummy'
sbindummy="$sbin/$dummy"

systemctl stop "$unit"

cp "$MY_DIR/$unit" "$systemd"
cp "$MY_DIR/$script" "$MY_DIR/$dummy" "$sbin"

chown kodi "$sbinscript" "$sbindummy"
chmod u+x "$sbinscript" "$sbindummy"

systemctl daemon-reload
systemctl start "$unit"
